version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.23.8
    restart: on-failure:0
    ports:
     - 8082:8082
     - 50051:50051
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./data"
      ENABLE_MODULES: text2vec-transformers
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: "http://uae-large-v1-inference:8080"
      CLUSTER_HOSTNAME: 'node1'
  uae-large-v1-inference:
    image: semitechnologies/transformers-inference:custom
    ports:
    - 8080:8080
    - 9090:9090
    volumes:
    - ./UAE-Large-V1:/app/models/model
    environment:
      ENABLE_CUDA: 1 # set to 1 to enable
      CLUSTER_HOSTNAME: 'node1'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
...